var express = require('express');
var router = express.Router();

const nameList= [
  {'Id': 1, 'Term':'Node.js', 'Description':'Node.js is an open-source, cross-platform runtime environment that allows developers to execute JavaScript code outside of a web browser. It is built on the Chrome V8 JavaScript engine and enables server-side scripting, making it possible to run JavaScript on the server, thus facilitating the development of scalable and efficient web applications.', 'reference':'S. Guerrero, MICROSERVICES IN SAP HANA XSA : a guide to rest apis using node.js. S.L.: Apress, 2020‌'}, 
  {'Id': 2, 'Term':'Deployment', 'Description':'Deployment  refers to the process of making a software application available and ready for use in a specific environment. It involves taking the code and other necessary resources of the application and setting them up in a way that users or customers can access and interact with the software. Deployment is a critical phase in the software development lifecycle as it takes the application from development and testing stages to production, where it serves its intended purpose.', 'reference':'C. K. Riemenschneider, B. C. Hardgrave, and F. D. Davis, “Explaining software developer acceptance of methodologies: a comparison of five theoretical models,” IEEE Transactions on Software Engineering, vol. 28, no. 12, pp. 1135–1145, Dec. 2002, doi: https://doi.org/10.1109/tse.2002.1158287.'}, 
  {'Id': 3, 'Term':'Software testing', 'Description':'Software testing is the process of evaluating and validating a software application to ensure that it meets the specified requirements, functions correctly, and delivers the intended results. It is a crucial phase in the software development lifecycle as it helps identify and correct software defects, errors, or discrepancies before it is deployed to end-users or customers. ', 'reference':'Y. Singh, Software testing. Cambridge: Cambridge University Press, 2013'}, 
  {'Id': 4, 'Term':'configuration', 'Description':'In software development, configuration refers to the process of customizing and setting up software applications to work correctly in a specific environment. This environment can be different stages of development (e.g., development, testing, staging, production) or various deployment targets (e.g., different servers, platforms, or client devices).', 'reference':'S. Berczuk and B. Appleton, Software Configuration Management Patterns. Addison-Wesley Professional, 2020.'}, 
  {'Id': 5, 'Term':'Data science', 'Description':'The main goal of data science is to leverage data to make data-driven decisions, solve complex problems, and gain a deeper understanding of the underlying patterns and phenomena in the data. Data scientists use their mathematics, statistics, programming, domain knowledge, and data visualization expertise to analyze data and draw meaningful conclusions.', 'reference':'F. Provost and T. Fawcett, “Data Science and its Relationship to Big Data and Data-Driven Decision Making,” Big Data, vol. 1, no. 1, pp. 51–59, Mar. 2013, doi: https://doi.org/10.1089/big.2013.1508.'}, 
  {'Id': 6, 'Term':'linux', 'Description':'Linux is an open-source.It  provides the core functionalities and services that an operating system requires, such as memory management, process management, device drivers, file system management, and networking.', 'reference':'S. G. Kochan and P. H. Wood, Shell programming in Unix, Linux and OS X. Indianapolis, Indiana: Addison-Wesley, 2017'}, 
  {'Id': 7, 'Term':'Cybersecurity', 'Description':'Cybersecurity, also known as information security, is the practice of protecting computer systems, networks, software, and data from unauthorized access, attacks, damage, theft, and other cybersecurity risks. It involves the implementation of measures and technologies to ensure the confidentiality, integrity, and availability of digital information and resources.', 'reference':'E. G. Amoroso, Cyber security. Summit, Nj: Silicon Press, 2017'}, 
  {'Id': 8, 'Term':'Version control', 'Description':'Version control, also known as source control or revision control, is a system and methodology used in software development to manage changes to source code and other files. It allows developers to track, document, and coordinate modifications made to a projects files over time', 'reference':'I. Kaur and H. Singh, “Advance Version Control (AVC): A Paradigm Shift from Version Control to Conflict Management,” International Journal of Computer Applications, vol. 167, no. 10, pp. 7–15, Jun. 2017, doi: https://doi.org/10.5120/ijca2017914384'}, 
  {'Id': 9, 'Term':' Big data ', 'Description':' Big data software solutions are designed to tackle the challenges posed by massive volumes of data, high velocity, diverse data types, and the need for real-time or near real-time data processing.', 'reference':'C. E. Otero and A. Peter, “Research Directions for Engineering Big Data Analytics Software,” IEEE Intelligent Systems, vol. 30, no. 1, pp. 13–19, Jan. 2015, doi: https://doi.org/10.1109/mis.2014.76.'}, 
  {'Id': 10, 'Term':'data visualization', 'Description':'In software development, data visualization refers to the process of displaying and presenting data in a visual format within software applications. It involves using graphical elements, such as charts, graphs, tables, maps, and other visual components, to represent complex datasets and information in a more understandable and insightful manner.', 'reference':'P. R. Holland, SAS programming and data visualization techniques : a power user’s guide. [Berkeley, CA]: Apress, 2015'}, 
   
  
  ];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Devops Glossary', sub:'Welcome to mywebsite showing a collection of Devops terms and their brief description', names:nameList});
});

module.exports = router;
