var express = require('express');
var router = express.Router();

const nameList= [
  {'Id': 1, 'Term':'Node.js', 'Description':'Node.js is an open-source, cross-platform runtime environment that allows developers to execute JavaScript code outside of a web browser. It is built on the Chrome V8 JavaScript engine and enables server-side scripting, making it possible to run JavaScript on the server, thus facilitating the development of scalable and efficient web applications.', 'reference':'S. Guerrero, MICROSERVICES IN SAP HANA XSA : a guide to rest apis using node.js. S.L.: Apress, 2020‌'}, 
  {'Id': 2, 'Term':'Deployment', 'Description':'Deployment  refers to the process of making a software application available and ready for use in a specific environment. It involves taking the code and other necessary resources of the application and setting them up in a way that users or customers can access and interact with the software. Deployment is a critical phase in the software development lifecycle as it takes the application from development and testing stages to production, where it serves its intended purpose.', 'reference':'C. K. Riemenschneider, B. C. Hardgrave, and F. D. Davis, “Explaining software developer acceptance of methodologies: a comparison of five theoretical models,” IEEE Transactions on Software Engineering, vol. 28, no. 12, pp. 1135–1145, Dec. 2002, doi: https://doi.org/10.1109/tse.2002.1158287.'}, 
  {'Id': 3, 'Term':'Software testing', 'Description':'Software testing is the process of evaluating and validating a software application to ensure that it meets the specified requirements, functions correctly, and delivers the intended results. It is a crucial phase in the software development lifecycle as it helps identify and correct software defects, errors, or discrepancies before it is deployed to end-users or customers. ', 'reference':'Y. Singh, Software testing. Cambridge: Cambridge University Press, 2013'}, 
  {'Id': 4, 'Term':'configuration', 'Description':'In software development, configuration refers to the process of customizing and setting up software applications to work correctly in a specific environment. This environment can be different stages of development (e.g., development, testing, staging, production) or various deployment targets (e.g., different servers, platforms, or client devices).', 'reference':'S. Berczuk and B. Appleton, Software Configuration Management Patterns. Addison-Wesley Professional, 2020.'}, 
  {'Id': 5, 'Term':'Data science', 'Description':'The main goal of data science is to leverage data to make data-driven decisions, solve complex problems, and gain a deeper understanding of the underlying patterns and phenomena in the data. Data scientists use their mathematics, statistics, programming, domain knowledge, and data visualization expertise to analyze data and draw meaningful conclusions.', 'reference':'F. Provost and T. Fawcett, “Data Science and its Relationship to Big Data and Data-Driven Decision Making,” Big Data, vol. 1, no. 1, pp. 51–59, Mar. 2013, doi: https://doi.org/10.1089/big.2013.1508.'}, 
  {'Id': 6, 'Term':'linux', 'Description':'Linux is an open-source.It  provides the core functionalities and services that an operating system requires, such as memory management, process management, device drivers, file system management, and networking.', 'reference':'S. G. Kochan and P. H. Wood, Shell programming in Unix, Linux and OS X. Indianapolis, Indiana: Addison-Wesley, 2017'}, 
  {'Id': 7, 'Term':'Cybersecurity', 'Description':'Cybersecurity, also known as information security, is the practice of protecting computer systems, networks, software, and data from unauthorized access, attacks, damage, theft, and other cybersecurity risks. It involves the implementation of measures and technologies to ensure the confidentiality, integrity, and availability of digital information and resources.', 'reference':'E. G. Amoroso, Cyber security. Summit, Nj: Silicon Press, 2017'}, 
  {'Id': 8, 'Term':'Version control', 'Description':'Version control, also known as source control or revision control, is a system and methodology used in software development to manage changes to source code and other files. It allows developers to track, document, and coordinate modifications made to a projects files over time', 'reference':'I. Kaur and H. Singh, “Advance Version Control (AVC): A Paradigm Shift from Version Control to Conflict Management,” International Journal of Computer Applications, vol. 167, no. 10, pp. 7–15, Jun. 2017, doi: https://doi.org/10.5120/ijca2017914384'}, 
  {'Id': 9, 'Term':' Big data ', 'Description':' Big data software solutions are designed to tackle the challenges posed by massive volumes of data, high velocity, diverse data types, and the need for real-time or near real-time data processing.', 'reference':'C. E. Otero and A. Peter, “Research Directions for Engineering Big Data Analytics Software,” IEEE Intelligent Systems, vol. 30, no. 1, pp. 13–19, Jan. 2015, doi: https://doi.org/10.1109/mis.2014.76.'}, 
  {'Id': 10, 'Term':'data visualization', 'Description':'In software development, data visualization refers to the process of displaying and presenting data in a visual format within software applications. It involves using graphical elements, such as charts, graphs, tables, maps, and other visual components, to represent complex datasets and information in a more understandable and insightful manner.', 'reference':'P. R. Holland, SAS programming and data visualization techniques : a power user’s guide. [Berkeley, CA]: Apress, 2015'}, 
  {'Id':11, 'Term':'Automation', 'Description': 'automation refers to the practice of using technology, scripts, tools, and processes to automate various tasks and workflows throughout the software development and delivery lifecycle.', 'reference':'D. Sato, Devops in Practice. Editora Casa do Código, 2014.'},
  {'Id':12, 'Term':'Agile', 'Description': 'Agile is a software development which aims to deliver valuable software to users more frequently and effectively by breaking down projects into smaller, manageable units of work called "sprints" or "iterations." ', 'reference':'Orit Hazzan and Y. Dubinsky, Agile software engineering. London: Springer, 2008.'},
{'Id':13, 'Term':'Two-factor authentication', 'Description': 'Two-factor authentication (2FA), also known as multi-factor authentication (MFA), is a security mechanism used to enhance the protection of online accounts and systems by requiring users to provide two or more different types of authentication factors to prove their identity before accessing their accounts.', 'reference':'R. A. Grimes, Hacking Multifactor Authentication. John Wiley & Sons, 2020.'},
{'Id':14, 'Term':'HTTP server', 'Description': 'HTTP server refers to a software application that serves web content over the Hypertext Transfer Protocol (HTTP). ', 'reference':'G. Blokdyk, Apache HTTP Server. Createspace Independent Publishing Platform, 2017.'},
{'Id':15, 'Term':'npm run', 'Description': 'The npm run command is used in Node.js and npm (Node Package Manager) to execute scripts defined in a projects package.json file. The npm run command is especially useful for automating common development tasks such as starting a development server, building production assets, running tests, and more. ', 'reference':'A. Patel, Hands-On Full-Stack Development with Swift : Develop full-stack web and native mobile applications using Swift and Vapor. Birmingham: Packt Publishing, 2018. '},
{'Id':16, 'Term':'Micro services', 'Description': 'Microservices is an architectural style in software development where a complex application is broken down into a set of smaller, loosely coupled, and independently deployable services. Each of these services represents a specific functionality or feature of the application', 'reference':'Irakli Nadareishvili, R. Mitra, M. McLarty, and M. Amundsen, Microservice Architecture. “O’Reilly Media, Inc.,” 2016.'},
{'Id':17, 'Term':'Docker', 'Description': 'Docker is a platform that enables developers to develop, ship, and run applications in containers. Containers are lightweight and portable environments that package together an applications code, runtime, libraries, and dependencies, allowing it to run consistently across different computing environments', 'reference':'Pethuru Raj, Learning Docker. 2017.'},
{'Id':18, 'Term':'open source', 'Description': 'Open source projects make their source code available to the public, allowing anyone to view, modify, and distribute the code according to the terms of the projects license.', 'reference':'ibrary And Information Technology Association (É.-U, Open source software for libraries : an open source for libraries collaboration. Chicago: Lita, 2002.'},
{'Id':19, 'Term':'Bootstrap', 'Description': 'Bootstrap is an open-source front-end framework used for designing and developing responsive and visually appealing websites and web applications. It provides a collection of HTML, CSS, and JavaScript components, templates, and tools that simplify the process of creating consistent and well-designed user interfaces.', 'reference':'A. Christian, S. Hesinto, and A. Agustina, “Rancang Bangun Website Sekolah Dengan Menggunakan Framework Bootstrap ( Studi Kasus SMP Negeri 6 Prabumulih ),” Jurnal Sisfokom (Sistem Informasi dan Komputer), vol. 7, no. 1, p. 22, Mar. 2018, doi: https://doi.org/10.32736/sisfokom.v7i1.278.'},
{'Id':20, 'Term':'DBMS', 'Description': 'DBMS stands for "Database Management System." Its a software system designed to manage, store, retrieve, and manipulate data in a structured and organized way. A DBMS provides an interface for users and applications to interact with databases, ensuring data integrity, security, and efficient data management.', 'reference':'B. L. Larson, SQL solutions for IBM DBMS. New York: Vnr Van Nostrand Reinhold, 1991.'},
{'Id':21, 'Term':'docker-image', 'Description':'A Docker image is a lightweight, stand-alone, and executable software package that includes everything needed to run a piece of software, including the code, runtime, system tools, system libraries, and settings.', 'reference':'J. S. Chelladhurai, V. Singh, and P. Raj, Learning Docker. Packt Publishing Ltd, 2017.'},
{'Id':22, 'Term':'.yaml file', 'Description':'A YAML file is a human-readable text-based data serialization format often used for configuration files, data exchange, and structured documents. ', 'reference':'N. Kebbani, P. Tylenda, and R. McKendrick, The Kubernetes bible: learn how to deploy and manage Kubernetes across every cloud platform. Birmingham: Packt Publishing, 2022.'},
{'Id':23, 'Term':' software deployment', 'Description':'Software deployment is the process of releasing, installing, and making a software application or system available for use in a specific environment.', 'reference':'Software architecture: moving from system content to deployment. New York: Ibm Press, 2016.'},
{'Id':24, 'Term':'Azure storage', 'Description':'Azure Storage is a cloud-based storage solution provided by Microsoft Azure, a cloud computing platform. It offers a variety of storage services designed to store and manage different types of data in the cloud. ', 'reference':'R. L. Nuckolls, Azure storage, streaming, and batch analytics: a guide for data engineers. Shelter Island, Ny: Manning Publications Co, 2020.'},
{'Id':25, 'Term':'command line interface', 'Description':'A Command Line Interface (CLI) is a text-based interface that allows users to interact with a computer system or software application by typing commands into a terminal or command prompt.', 'reference':'R. Aley, PHP CLI Create Command Line Interface Scripts with PHP. Berkeley, Ca Apress, 2016.'},
{'Id':26, 'Term':'local host port', 'Description':'A localhost port, often referred to as a "listening port," is a specific communication endpoint on a computers local network interface. Its used to establish network connections for various applications and services running on the same machine. ', 'reference':'Elliotte Rusty Harold, Java network programming. Cambridge; Sebastopol: reilly, 2000.'},
{'Id':27, 'Term':'cloud computing', 'Description':'Cloud computing refers to the delivery of various computing services—such as storage, processing power, networking, databases, and software—over the internet ("the cloud").', 'reference':'N. B. Ruparelia, Cloud computing. Cambridge, Massachusetts; London, England: The Mit Press, 2018.'},
{'Id':28, 'Term':'disk storage', 'Description':'In Azure Storage, "disk storage" generally refers to the ability to attach and use virtual disks with Azure Virtual Machines.', 'reference':'M. Waly, Learning Microsoft Azure Storage. Packt Publishing Ltd, 2017.'},
{'Id':29, 'Term':'visual studio', 'Description':'Visual Studio is a powerful integrated development environment (IDE) created by Microsoft for building a wide range of software applications, including web applications, desktop applications, mobile apps, cloud services, and more.', 'reference':'B. Johnson, Professional Visual Studio 2017. Indianapolis John Wiley & Sons Cop, 2018.'},
{'Id':30, 'Term':'data handling', 'Description':'Data handling, also known as data management, refers to the process of acquiring, storing, organizing, processing, analyzing, and ensuring the quality and security of data. ', 'reference':'A. Montague-Smith, Data handling : Year 3. Leamington Spa: Scholastic, 2011.'}
  
  ];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Devops Glossary', sub:'Welcome to mywebsite showing a collection of Devops terms and their brief description', names:nameList});
});

module.exports = router;
